Improve argument checking in generate-release-notes script

diff --git a/bin/generate-release-notes b/bin/generate-release-notes
--- a/bin/generate-release-notes
+++ b/bin/generate-release-notes
@@ -1,9 +1,24 @@
 #!/usr/bin/env bash
 
 PREVIOUS_VERSION=$1
+
 if [ -z $PREVIOUS_VERSION ]; then
-    echo "Usage:   generate-release-notes VERSION [--all]"
-    echo "Example: generate-release-notes 6.0.1"
+    cat <<-INFO
+NAME:
+  generate-release-notes - Generate release notes relative to a given version
+
+USAGE:
+  generate-release-notes PREVIOUS_VERSION [--all]
+
+EXAMPLE:
+  generate-release-notes 6.0.1
+INFO
+
+    exit 1
+fi
+
+if [ -z $(echo $PREVIOUS_VERSION | grep -e 'v') ]; then
+    echo "Error - PREVIOUS_VERSION argument should have this form: v6.0.1"
     exit 1
 fi
 
@@ -12,7 +27,7 @@ if [ "$2" = "--all" ]; then
   SHOW_ALL_COMMITS=true
 fi
 
-VERSION=$(cat VERSION)
+VERSION=v$(cat VERSION)
 
 cat <<-NOTES
 CF version $VERSION
@@ -20,21 +35,21 @@ CF version $VERSION
 
 Installers
 ----------
-- [Debian 32 bit](https://s3.amazonaws.com/go-cli/releases/v$VERSION/cf-cli_i386.deb)
-- [Debian 64 bit](https://s3.amazonaws.com/go-cli/releases/v$VERSION/cf-cli_amd64.deb)
-- [Redhat 32 bit](https://s3.amazonaws.com/go-cli/releases/v$VERSION/cf-cli_i386.rpm)
-- [Redhat 64 bit](https://s3.amazonaws.com/go-cli/releases/v$VERSION/cf-cli_amd64.rpm)
-- [Mac OS X 64 bit](https://s3.amazonaws.com/go-cli/releases/v$VERSION/installer-osx-amd64.pkg)
-- [Windows 32 bit](https://s3.amazonaws.com/go-cli/releases/v$VERSION/installer-windows-386.zip)
-- [Windows 64 bit](https://s3.amazonaws.com/go-cli/releases/v$VERSION/installer-windows-amd64.zip)
+- [Debian 32 bit](https://s3.amazonaws.com/go-cli/releases/$VERSION/cf-cli_i386.deb)
+- [Debian 64 bit](https://s3.amazonaws.com/go-cli/releases/$VERSION/cf-cli_amd64.deb)
+- [Redhat 32 bit](https://s3.amazonaws.com/go-cli/releases/$VERSION/cf-cli_i386.rpm)
+- [Redhat 64 bit](https://s3.amazonaws.com/go-cli/releases/$VERSION/cf-cli_amd64.rpm)
+- [Mac OS X 64 bit](https://s3.amazonaws.com/go-cli/releases/$VERSION/installer-osx-amd64.pkg)
+- [Windows 32 bit](https://s3.amazonaws.com/go-cli/releases/$VERSION/installer-windows-386.zip)
+- [Windows 64 bit](https://s3.amazonaws.com/go-cli/releases/$VERSION/installer-windows-amd64.zip)
 
 Binaries
 --------
-- [Linux 32 bit binary]   (https://s3.amazonaws.com/go-cli/releases/v$VERSION/cf-linux-386.tgz)
-- [Linux 64 bit binary]   (https://s3.amazonaws.com/go-cli/releases/v$VERSION/cf-linux-amd64.tgz)
-- [Mac OS X 64 bit binary](https://s3.amazonaws.com/go-cli/releases/v$VERSION/cf-darwin-amd64.tgz)
-- [Windows 32 bit binary] (https://s3.amazonaws.com/go-cli/releases/v$VERSION/cf-windows-386.zip)
-- [Windows 64 bit binary] (https://s3.amazonaws.com/go-cli/releases/v$VERSION/cf-windows-amd64.zip)
+- [Linux 32 bit binary]   (https://s3.amazonaws.com/go-cli/releases/$VERSION/cf-linux-386.tgz)
+- [Linux 64 bit binary]   (https://s3.amazonaws.com/go-cli/releases/$VERSION/cf-linux-amd64.tgz)
+- [Mac OS X 64 bit binary](https://s3.amazonaws.com/go-cli/releases/$VERSION/cf-darwin-amd64.tgz)
+- [Windows 32 bit binary] (https://s3.amazonaws.com/go-cli/releases/$VERSION/cf-windows-386.zip)
+- [Windows 64 bit binary] (https://s3.amazonaws.com/go-cli/releases/$VERSION/cf-windows-amd64.zip)
 
 Change Log
 ----------
@@ -42,11 +57,11 @@ NOTES
 
 if [ -z $SHOW_ALL_COMMITS ]; then
   git --no-pager log \
-    v$PREVIOUS_VERSION..v$VERSION \
+    $PREVIOUS_VERSION..$VERSION \
     --grep "\[.*\d*\]" \
     --pretty=format:'#### %s%n%b'
 else
   git --no-pager log \
-    v$PREVIOUS_VERSION..v$VERSION \
+    $PREVIOUS_VERSION..$VERSION \
     --pretty=format:'#### %s%n%b'
 fi
