verify that new phrases can be added to i18n files
[finishes #126409711]

Signed-off-by: Difan Zhao <dzhao@pivotal.io>

diff --git a/bin/i18n-checkup b/bin/i18n-checkup
--- a/bin/i18n-checkup
+++ b/bin/i18n-checkup
@@ -1,16 +1,12 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-set +e
+set -ex
 
-export PATH=$PATH:$GOPATH/bin
-ROOT_DIR=$(cd $(dirname $(dirname $0)) && pwd)
-
-function killed {
-  exit 1
+mkdir lang_temp
+function cleanup {
+   rm -rf lang_temp
 }
-trap killed SIGINT
-
-echo -e "\n Updating translation files"
+trap cleanup EXIT
 
 if [ ! $(which goi18n) ];then
   echo -e "\n Installing go-i18n..."
@@ -18,17 +14,22 @@ if [ ! $(which goi18n) ];then
 fi
 
 echo -e "\n Updating i18n4go..."
-go get -u github.com/krishicks/i18n4go/i18n4go
+go get -u github.com/XenoPhex/i18n4go/i18n4go
 if [ $? -ne 0 ]; then
-  printf "Failed to run `go get -u github.com/krishicks/i18n4go/i18n4go`"
+  printf "Failed to run `go get -u github.com/XenoPhex/i18n4go/i18n4go`"
   exit 1
 fi
 
-i18n4go -c fixup
-if [ $? -ne 0 ]; then
-  printf "Failed to run `i18n4go -c fixup`"
-  exit 1
-fi
+
+IGNORE_FILES_REGEX=".*test.go|.*resources.go|fake.*\.go|template.go"
+
+i18n4go -c extract-strings -e excluded.json -s specialStrings.json -o lang_temp -d commands -r --ignore-regexp $IGNORE_FILES_REGEX
+i18n4go -c extract-strings -e excluded.json -s specialStrings.json -o lang_temp -d cf -r --ignore-regexp $IGNORE_FILES_REGEX
+i18n4go -c merge-strings -v -d lang_temp
+
+i18n4go -c fixup --source-language-file lang_temp/en.all.json
+
+set +e
 
 goi18n -outdir cf/i18n/resources cf/i18n/resources/*.all.json
 if [ $? -ne 0 ]; then
@@ -43,3 +44,4 @@ if [[ $(git status --porcelain cf/i18n/resources) ]]; then
     exit 1
   fi
 fi
+
