Backport bin scripts and CI goodness

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,30 +1,30 @@
 #!/bin/bash
 
-set -e
+(
+  set -e
 
-function printStatus {
-    if [ $? -eq 0 ]; then
-        echo -e "\nSUITE SUCCESS"
-    else
-        echo -e "\nSUITE FAILURE"
-    fi
-}
+  function printStatus {
+      if [ $? -eq 0 ]; then
+          echo -e "\nSWEET SUITE SUCCESS"
+      else
+          echo -e "\nSUITE FAILURE"
+      fi
+  }
 
-trap printStatus EXIT
+  trap printStatus EXIT
 
-echo -e "\n Formatting packages..."
-$(dirname $0)/go fmt cf/...
+  echo -e "\n Formatting packages..."
+  bin/go fmt cf/... testhelpers/... generic/... main/... glob/... words/...
 
-echo -e "\n Installing package dependencies..."
-$(dirname $0)/go test -i cf/... generic/...
+  echo -e "\n Installing package dependencies..."
+  bin/go test -i cf/... generic/...
 
-echo -e "\n Testing packages:"
-$(dirname $0)/go test cf/... generic/... -parallel 4$@
+  echo -e "\n Testing packages:"
+  bin/go test cf/... generic/... -parallel 4$@
 
-echo -e "\n Vetting packages for potential issues..."
-$(dirname $0)/go tool vet src/cf/.
+  echo -e "\n Vetting packages for potential issues..."
+  bin/go tool vet src/cf/.
 
-echo -e "\n Running build script to confirm everything compiles..."
-$(dirname $0)/build
-
-
+  echo -e "\n Running build script to confirm everything compiles..."
+  bin/build
+)
