Verify Golang version in v7 pipeline
[#169279148](https://www.pivotaltracker.com/story/show/169279148)

Co-authored-by: Brendan Smith <brsmith@pivotal.io>

diff --git a/cli-v7/tasks/build-binaries.yml b/cli-v7/tasks/build-binaries.yml
--- a/cli-v7/tasks/build-binaries.yml
+++ b/cli-v7/tasks/build-binaries.yml
@@ -26,6 +26,12 @@ run:
     export GOPATH=$PWD/gopath
     export PATH=$GOPATH/bin:$PATH
 
+    export TARGET_GO_VERSION=${TARGET_GO_VERSION:-"UNSET"}
+
+    if go version | grep -v "\b$TARGET_GO_VERSION\b"; then
+      echo "ERROR: expected target go version [ $TARGET_GO_VERSION ]"
+      exit 1
+
     go version
 
     mv i18n-data/i18n_resources.go $GOPATH/src/code.cloudfoundry.org/cli/i18n/resources
