Check for gofmt in pre-commit hook
[#119023379]

Signed-off-by: Chris Hendrix <chendrix@pivotal.io>

diff --git a/bin/githooks/pre-commit b/bin/githooks/pre-commit
--- a/bin/githooks/pre-commit
+++ b/bin/githooks/pre-commit
@@ -41,7 +41,7 @@ If you know what you are doing you can disable this check using:
 
   git config hooks.allownonascii true
 EOF
-        exit 1
+        return 1
     fi
 
     # If there are whitespace errors, print the offending file names and fail.
@@ -52,5 +52,38 @@ ratchet () {
     $ROOT_DIR/bin/ratchet
 }
 
+gofmt () {
+    # Copyright 2012 The Go Authors. All rights reserved.
+    # Use of this source code is governed by a BSD-style
+    # license that can be found in the LICENSE file.
+
+    # git gofmt pre-commit hook
+    #
+    # To use, store as .git/hooks/pre-commit inside your repository and make sure
+    # it has execute permissions.
+    #
+    # This script does not handle file names that contain spaces.
+
+    set +e
+    gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '.go$')
+    set -e
+    [ -z "$gofiles" ] && return 0
+
+    set +e
+    unformatted=$(gofmt -l $gofiles)
+    set -e
+    [ -z "$unformatted" ] && return 0
+
+    # Some files are not gofmt'd. Print message and fail.
+
+    echo "Go files must be formatted with gofmt. Please run:"
+    for fn in $unformatted; do
+        echo "  gofmt -w $PWD/$fn"
+    done
+
+    return 1
+}
+
 non_ascii_filenames
+gofmt
 ratchet
