Verify Golang version in v7 pipeline
[#169279148](https://www.pivotaltracker.com/story/show/169279148)

Co-authored-by: Brendan Smith <brsmith@pivotal.io>

diff --git a/ci/cli-v7/tasks/build-osx-binary.yml b/ci/cli-v7/tasks/build-osx-binary.yml
--- a/ci/cli-v7/tasks/build-osx-binary.yml
+++ b/ci/cli-v7/tasks/build-osx-binary.yml
@@ -20,6 +20,12 @@ run:
     cwd=$PWD
     export GOPATH=$PWD/gopath
     export PATH=$GOPATH/bin:$PATH
+    export TARGET_GO_VERSION=${TARGET_GO_VERSION:-"UNSET"}
+
+    if go version | grep -v "\b$TARGET_GO_VERSION\b"; then
+      echo "ERROR: expected target go version [ $TARGET_GO_VERSION ]"
+      exit 1
+    fi
 
     go version
 
